### ISSUE TITLE
Revisar imágenes rotas

### ISSUE THREAD

**Issue by adriancast** [adriancast/tigeraso#9]
Hay url de imágenes rotas debido a que las imágenes de los JSON no están en el path correcto o no existen. 

Hay que revisar por que no se pintan

**Comment by michellevlad** [comment]
Fixed links photos in the json event.
En las paginas de cada producto se ven las fotos pero en la pagina de resultados ni en home no se ven.

**Comment by michellevlad** [comment]
Fixed by @adriancast , event.images[1]-->event.images[0]
